eme-extension-policy-check.md

Make the API easier to use by replacing the opaque policy object
with a simple javascript interface.
Of course, this means we have to define the interface. For now we
are only interested in policies regarding HDCP.

Rework EME policy proposal

---

eme-extension-policy-check.md

Responding to feedback. We chose to return MediaKeyStatus (rather than a bool) for extensibility. Later on we may wish to add other license components to the MediaKeysPolicy query and will benefit from the full range of values in MediaKeyStatus.

Clarify eme key status

---

index.bs

Tiny fix, ToT sections read:
>    3.5 Examples 
>    3.6 Query recording capabilities with encodingInfo()
And it should read:
> 4 Examples
> 4.1Query recording capabilities with encodingInfo()
This PR corrects it.

Fix wrong section header levels in Examples

---

index.bs

This is adding clear wording around MIME type requirements such as
codecs being required.
This is also requiring the framerate for VideoConfiguration to be a
finite value and greater than 0.

Strengthen {Audio,Video}Configuration validity (fixes #1, fixes #23, fixes #32).

---

index.bs

Reverts WICG/media-capabilities#33

Revert "Use `bandwidth` instead of `bitrate` for consistency with DASH and HLS (fixes #27)"

---

eme-extension-policy-check.md

Until this is decided, we should align `minHdcpVersion` values with Chromium implementation: https://chromium.googlesource.com/chromium/src/+/master/media/blink/webcontentdecryptionmodule_impl.cc#36

Update minHdcpVersion value

---

index.bs

Video bitrate already crossed the 4B limit for raw video streams (e.g. 24 bit, 4K @ 60 fps ~ 11 Gbps), compressed streams are catching up (https://en.wikipedia.org/wiki/Ultra_HD_Blu-ray).
Audio bitrate upgraded for the data consistency.

Upgrade bitrate to 64 bit integer.

---

index.bs

Also lowercase the variable, even if it'll look funny.

Fix a typo in "configuration's framerate"

---

explainer.md

Initially just to fix "video/webm codec=vp9.0", but code was tested in
Chrome Canary and tweaked until it mostly works. Examples of future APIs
obviously still don't work.

Update the explain example code to mostly work

---

index.bs

contentType is not defined within .then() or .catch(), substitute result.contentType and add err argument at catch callback function and console.error(). Remove extra }); following .catch(()=>{});.

Fix Example 1

---

index.bs

Only contains a few booleans at this time, so lets use a dictionary rather than interface.
Resolves #97.

Make MediaCapabilitiesInfo a dictionary.

---

explainer.md

Existing code was working. Using `map()` makes it easier to read for web developers though.
WDYT?

Update encryption JS example

---

index.bs

Initial commit to add IDL and algorithms for describing encrypted
media (EME). This takes a normative reference on the EME spec and
offloads as much as possible to the existing algorithms there.
There are a handful of FIXME's here to track open issues needing
resolution before merge.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/pull/101.html" title="Last updated on Nov 20, 2018, 1:58 AM GMT (2f791d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/101/feabd16...2f791d7.html" title="Last updated on Nov 20, 2018, 1:58 AM GMT (2f791d7)">Diff</a>

Suport querying decodingInfo() for encrypted media.

---

index.bs

TypeError is preferred for invalid input, so its confusing to use for
this reason.
Fixes #106.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/pull/108.html" title="Last updated on Nov 30, 2018, 9:54 PM GMT (b550f9b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/108/a16dfb5...b550f9b.html" title="Last updated on Nov 30, 2018, 9:54 PM GMT (b550f9b)">Diff</a>

Throw InvalidStateError for EME in workers.

---

index.bs

This typo _rubbed_ me the wrong way. (...I'll see myself out. 😅)
***
<a href="https://pr-preview.s3.amazonaws.com/MattiasBuelens/media-capabilities/pull/109.html" title="Last updated on Jan 3, 2019, 1:56 PM UTC (2516ec4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/109/9bbcdaa...MattiasBuelens:2516ec4.html" title="Last updated on Jan 3, 2019, 1:56 PM UTC (2516ec4)">Diff</a>

Fix typo in "robustness"

---

index.bs

Fixes Issue #112.
***
<a href="https://pr-preview.s3.amazonaws.com/jernoble/media-capabilities/pull/114.html" title="Last updated on Jun 3, 2019, 7:16 PM UTC (e1e4e6b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/114/66baccc...jernoble:e1e4e6b.html" title="Last updated on Jun 3, 2019, 7:16 PM UTC (e1e4e6b)">Diff</a>

Add support for `hasAlphaChannel` in VideoConfiguration.

---

CONTRIBUTING.md
LICENSE.md
explainer.md
index.bs
security-privacy-questionnaire.md
w3c.json

- Update spec boilerplate (copyright, status of this document section) to note that the Media WG now publishes the spec.
- Update self-references from `wicg.github.io` to `w3c.github.io`
- Add `w3c.json` file for repo tracking purpose.
- Drop local biblio for Media Playback Quality (now in specref)
Note the PR depends on https://github.com/tabatkins/bikeshed/pull/1498
... and should only be merged once the repo has been transferred to the W3C organization (#117)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/media-capabilities/pull/125.html" title="Last updated on Jul 24, 2019, 2:33 PM UTC (18ff294)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/125/2980f6f...tidoust:18ff294.html" title="Last updated on Jul 24, 2019, 2:33 PM UTC …

Update spec info to point to Media WG

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/128.html" title="Last updated on Aug 15, 2019, 12:15 AM UTC (96c22d3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/128/a6370dc...96c22d3.html" title="Last updated on Aug 15, 2019, 12:15 AM UTC (96c22d3)">Diff</a>

Revert VideoConfiguration.framerate to a double. Fixes #96

---

index.bs

Fixes #111.
***
<a href="https://pr-preview.s3.amazonaws.com/jernoble/media-capabilities/pull/115.html" title="Last updated on Jun 3, 2019, 6:06 PM UTC (47615ce)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/media-capabilities/115/66baccc...jernoble:47615ce.html" title="Last updated on Jun 3, 2019, 6:06 PM UTC (47615ce)">Diff</a>

Expose "configuration" to the DOM.

---

explainer.md

Update the explainer to include a section for spatial audio, which includes justifications for the WebAPI and instructions for using it. This PR follows up on the merging of #123. 
+@scottlow
+@GurpreetV
+@gregwhitworth
+@isuru-c-p

Add Spatial Audio to the explainer

---

index.bs

We previously prefixed robustness dict-members with 'audio' and
'video'. We now nest them under audio/video dicts to allow for
more elegant expansion of audio/video-specific fields alongside
robustness. Ex: encryptionScheme. See #100.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/138.html" title="Last updated on Oct 24, 2019, 7:04 PM UTC (89a303f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/138/4844eaa...89a303f.html" title="Last updated on Oct 24, 2019, 7:04 PM UTC (89a303f)">Diff</a>

Add audio/video attributes to key system config.

---

index.bs

Minor editorial updates to fix a few broken links and correct references:
- Make sure that spec name used in custom dfns matches name in Bikeshed's biblio
- Make sure that base URL used in custom dfns matches the one used in references
- Fix broken fragments in custom dfns
- Fix duplicated section IDs
- Drop mention of HTML52 in favor of HTML LS
- Flag mentions of MediaStream Recording and WebRTC as informative so that references appear in the right list
Also replaced links that return permanent redirects (301) with final URL (needed to publish the document as FPWD)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/media-capabilities/pull/143.html" title="Last updated on Jan 14, 2020, 11:31 AM UTC (2294043)">Preview</a> | <a …

Fix broken links, missing and incorrect references

---

index.bs

Encryption scheme is now part of the EME editors draft. This patch updates MediaCapabilities to include it alongside robustness. 
Fixes #100
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/144.html" title="Last updated on Jan 23, 2020, 7:32 AM UTC (c68b503)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/144/4d5d0fb...c68b503.html" title="Last updated on Jan 23, 2020, 7:32 AM UTC (c68b503)">Diff</a>

Add encryption scheme to KeySystemTrackConfiguration

---

index.bs

Web Workers are no longer being worked upon in W3C. Reference needs to be to the HTML LS spec. Bikeshed does the right thing on its own, we just need to stay out of the way...
Requested for publication to First Public Working Draft:
https://github.com/w3c/transitions/issues/213#issuecomment-579255649
(Nothing urgent with regards to this PR, I made the change manually on the document that is about to be published)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/media-capabilities/pull/148.html" title="Last updated on Jan 28, 2020, 2:58 PM UTC (9cdb6f7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/148/d573555...tidoust:9cdb6f7.html" title="Last updated on Jan 28, 2020, 2:58 PM UTC (9cdb6f7)">Diff</a>

Drop custom reference for WorkerGlobalScope

---

index.bs

This PR makes a few improvements to the `encodingInfo()` example, in response to #149:
- Fix use of `contentType`
- Improve error message
- Minor code layout change
***
:boom: ###
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 12, 2020, 11:53 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fmedia-capabilities%2Fpull%2F150%2F0c65f07.html&doc2=https%3A%2F%2Fpr-preview …

Impove encodingInfo() example

---

index.bs

See #147
***
:boom: ###
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 13, 2020, 9:47 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fw3c%2Fmedia-capabilities%2Fpull%2F151%2F0c65f07.html&doc2=https%3A%2F%2Fpr-preview.s3.amazonaws.com%2Fchrisn%2Fmedia-capabilities%2Fpull%2F151.html)
_If you don't have enough information above to solve the error by yourself (or to …

Add decodingInfo() example

---

index.bs

The `encodingInfo()` WebIDL currently shows the return type as `Promise<MediaCapabilitiesInfo>`, which I think should be `Promise<MediaCapabilitiesEncodingInfo>`.
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/media-capabilities/pull/154.html" title="Last updated on Jun 26, 2020, 2:21 PM UTC (edeb3b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/154/a9bdf79...chrisn:edeb3b0.html" title="Last updated on Jun 26, 2020, 2:21 PM UTC (edeb3b0)">Diff</a>

Fix encodingInfo() return type

---

index.bs

The "present" concept for dictionary members was dropped from WebIDL, see:
https://github.com/heycam/webidl/commit/8d4e7ca67bcb4de476aab0411531dc97f6d17e0d
The recommendation is to rather link to the "exist" concept for maps, defined in the infra spec:
https://infra.spec.whatwg.org/#map-exists
This update fixes broken links to "present" accordinly.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/media-capabilities/pull/161.html" title="Last updated on Dec 10, 2020, 10:15 AM UTC (ef5228a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/161/422ee44...tidoust:ef5228a.html" title="Last updated on Dec 10, 2020, 10:15 AM UTC (ef5228a)">Diff</a>

Replace now gone "present" concept with "exist"

---

index.bs

This PR extends the MediaCapabilities API to the WebRTC use case.
-Add webrtc to MediaDecodingType
-Change transmission to webrtc to MediaEncodingType
-Clarify MIME types for webrtc.
-Add scalabilityMode to VideoConfiguration.
***
<a href="https://pr-preview.s3.amazonaws.com/drkron/media-capabilities/pull/158.html" title="Last updated on Oct 19, 2020, 11:39 AM UTC (d7ee8fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/158/7261f8f...drkron:d7ee8fd.html" title="Last updated on Oct 19, 2020, 11:39 AM UTC (d7ee8fd)">Diff</a>

Extend MediaCapabilities API to WebRTC

---

index.bs

Fixing some dfn links, white space, and line wrapping.
Remove mention of display fingerprinting. This lingered from earlier draft when we proposed changes to CSSOM Screen. Presently there are no display capabilities described in this spec.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/164.html" title="Last updated on Feb 22, 2021, 5:58 AM UTC (168a2a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/164/4f45937...168a2a4.html" title="Last updated on Feb 22, 2021, 5:58 AM UTC (168a2a4)">Diff</a>

Minor cleanup

---

.gitattributes

With this PR, [index.bs](https://github.com/w3c/media-capabilities/blob/main/index.bs) will be syntax highlighted. See https://github.com/github/linguist/blob/master/docs/overrides.md
The result seems to be better than `linguist-language=Markdown`.

Highlight .bs files as HTML

---

index.bs

Fixes #182
***
<a href="https://pr-preview.s3.amazonaws.com/drkron/media-capabilities/pull/189.html" title="Last updated on Feb 8, 2022, 10:36 PM UTC (ee9acf7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/189/7cfc693...drkron:ee9acf7.html" title="Last updated on Feb 8, 2022, 10:36 PM UTC (ee9acf7)">Diff</a>

Add spatialScalability to VideoConfiguration

---

index.bs

Fixes #187
***
<a href="https://pr-preview.s3.amazonaws.com/drkron/media-capabilities/pull/193.html" title="Last updated on Apr 12, 2022, 11:55 AM UTC (22f5c1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/193/32d34de...drkron:22f5c1c.html" title="Last updated on Apr 12, 2022, 11:55 AM UTC (22f5c1c)">Diff</a>

Specify in which contexts optional members are applicable

---

index.bs

This PR updates some references:
- Update RFC7231 with RFC9110 (HTTP Semantics)
- Remove local biblio entry for webrtc (fixes a bikeshed warning)
I also tidied up the IDL blocks to use `<xmp>` throughout.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/198.html" title="Last updated on Aug 1, 2022, 3:15 PM UTC (57a14f3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/198/9290845...57a14f3.html" title="Last updated on Aug 1, 2022, 3:15 PM UTC (57a14f3)">Diff</a>

Update references and replace <pre> with <xmp> for IDL blocks

---

index.bs

The Secure Contexts spec no longer has an algorithm named "Is the environment settings object settings a secure context?". That part got merged into HTML. This update adjusts the text accordingly, fixing the broken link.
It also drops custom definitions of all terms that are now part of Bikeshed's autolinking database. Remaining ones are needed because underlying specs are not yet in the database.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/media-capabilities/pull/201.html" title="Last updated on Dec 8, 2022, 4:54 PM UTC (defebc5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/201/8312135...tidoust:defebc5.html" title="Last updated on Dec 8, 2022, 4:54 PM UTC (defebc5)">Diff</a>

Adjust ref to secure context and shrink hardcoded xref links

---

index.bs

Publication to /TR currently fails because spec editors must be working group participants, and Will is no longer around. This is per W3C Process, see: https://www.w3.org/2023/Process-20231103/#publication
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/214.html" title="Last updated on Feb 9, 2024, 7:28 AM UTC (6b2e006)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/214/b47e97e...6b2e006.html" title="Last updated on Feb 9, 2024, 7:28 AM UTC (6b2e006)">Diff</a>

Move Will Cassella to former editor

---

index.bs

closes #44
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/221.html" title="Last updated on Jul 4, 2024, 9:06 AM UTC (c049038)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/221/1774c15...c049038.html" title="Last updated on Jul 4, 2024, 9:06 AM UTC (c049038)">Diff</a>

add definition of power efficient, remove battery note

---

index.bs

This PR updates the introduction to explain that display capability detection happens elsewhere, and removes mention of Media Playback Quality.
It also fixes a few grammatical issues I found elsewhere in the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/media-capabilities/pull/204.html" title="Last updated on Jul 18, 2024, 10:55 AM UTC (64f4164)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/204/35e5eaa...chrisn:64f4164.html" title="Last updated on Jul 18, 2024, 10:55 AM UTC (64f4164)">Diff</a>

Update introduction section

---

index.bs

This PR fixes a typo "renderering", the emphasis around "for the current audio device" seemed unnecessary, and clarifies `spatialRendering` the dictionary member vs the activity of spatial rendering.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/211.html" title="Last updated on Jan 12, 2024, 5:21 PM UTC (2622504)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/211/b47e97e...2622504.html" title="Last updated on Jan 12, 2024, 5:21 PM UTC (2622504)">Diff</a>

Minor editorial tweak to spatialRendering definition

---

index.bs

See #224.
Depends on https://github.com/w3c/encrypted-media/pull/555 and https://github.com/w3c/encrypted-media/pull/557.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/225.html" title="Last updated on Aug 7, 2024, 4:31 PM UTC (952eb85)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/225/a5b96e1...952eb85.html" title="Last updated on Aug 7, 2024, 4:31 PM UTC (952eb85)">Diff</a>

Update references to EME terms

---

Makefile

This adds a couple of quality of life shortcuts for spec editing.
- `make lint` is a dry-run of bikeshed that reports any errors and warnings.
- `make watch` dynamically regenerates the spec when the source is updated.

Update Makefile with lint and watch.

---

Makefile
index.bs

Closes #229 by adding a media capabilities task source, and using it to resolve the promises created 
by `decodingInfo()` and `encodingInfo()`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/232.html" title="Last updated on Oct 4, 2024, 11:55 PM UTC (8cd3baf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/232/6b47236...8cd3baf.html" title="Last updated on Oct 4, 2024, 11:55 PM UTC (8cd3baf)">Diff</a>

Adds a task source and uses it for resolving promises.

---

index.bs

Closes #69 
this is a draft... it doesn't actually address all the issues with MIME usage yet... just a start.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/222.html" title="Last updated on Dec 17, 2024, 12:16 AM UTC (7001dec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/222/e2c7d31...7001dec.html" title="Last updated on Dec 17, 2024, 12:16 AM UTC (7001dec)">Diff</a>

Fixup MIME usage

---

index.bs

New HTML parser in Bikeshed is less lax about invalid HTML constructs. The spec had a number of places where it nested `<ol>` or `<ul>` within `<p>`, which isn't allowed in HTML. This PR fixes the markup.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/239.html" title="Last updated on Feb 6, 2025, 10:53 AM UTC (e734cc9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/239/f5b9f6a...e734cc9.html" title="Last updated on Feb 6, 2025, 10:53 AM UTC (e734cc9)">Diff</a>

[Editorial] Fix HTML markup in source

---

index.bs

Resolves #192.
Adds text about how to interpret width and height when `scalabilityMode` is set.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/236.html" title="Last updated on Oct 15, 2024, 9:33 PM UTC (54af3fc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/236/e2c7d31...54af3fc.html" title="Last updated on Oct 15, 2024, 9:33 PM UTC (54af3fc)">Diff</a>

Add text about how to interpret width and height.

---

index.bs

Fixes https://github.com/w3c/media-capabilities/issues/243
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/media-capabilities/pull/244.html" title="Last updated on May 13, 2025, 12:38 PM UTC (f651785)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/244/f5a99e6...youennf:f651785.html" title="Last updated on May 13, 2025, 12:38 PM UTC (f651785)">Diff</a>

Make MediaCapabilitiesDecodingInfo and MediaCapabilitiesEncodingInfo configuration member required

---

index.bs

[WebRTC-SVC Section 7.1](https://w3c.github.io/webrtc-svc/#persistent-information) includes text relating to `spatialScalability` which appears more appropriate for the Media Capabilities specification. 
 
Related: https://github.com/w3c/webrtc-svc/issues/103
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/218.html" title="Last updated on Jun 12, 2025, 11:27 AM UTC (60fb9d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/218/1774c15...60fb9d2.html" title="Last updated on Jun 12, 2025, 11:27 AM UTC (60fb9d2)">Diff</a>

Clarify meaning of spatialScalability
