w3c/media-capabilities

- index.bs
@chcunningham @miguelao @uysalere PTAL :)
> Add support for encoding abilities (fixes #28)

- index.bs
> Use `bandwidth` instead of `bitrate` for consistency with DASH and HLS (fixes #27)

- index.bs
> Remove pixelDepth and colorDepth from partial Screen interface (#4).

- eme-extension-policy-check.md
> Update HDCP proposal to use dictionary (fixes #49)

- index.bs
> Make framerate a DOMString so it can be expressed as a fraction (fixes #12)

- eme-extension-policy-check.md
> Updated privacy considerations

- index.bs
Expansion of the definition to address CBR versus VBR streams.
> Add language to handle the VBR use case.

- index.bs
> Remove duplicate paragrah (fixes #61)

- index.bs
> Clarify what width/height mean for a video (fixes #11).

- explainer.md
Re: Issue #47
Hello world! Some open issues to adddress, but I'd like to create
a public record of those discussions and start getting broader
feedback.
> Update explainer with latest Encryption proposal

- index.bs
> Expose MediaCapabilitiesInfo to (Window, Worker)

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/127.html" title="Last updated on Aug 14, 2019, 11:40 PM UTC (974adf2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/127/15ef142...974adf2.html" title="Last updated on Aug 14, 2019, 11:40 PM UTC (974adf2)">Diff</a>
> Add Chris Cunningham as editor.

- explainer.md
Update the HDR section of the explainer in light of discussions on #118 and the merging of #135. The WIP nature of screen capabilities is acknowledged. 
+@scottlow
+@GurpreetV
+@gregwhitworth
+@isuru-c-p
> Update HDR section of explainer

- index.bs
Resolved at TPAC 2019.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/145.html" title="Last updated on Jan 23, 2020, 5:49 PM UTC (9801ee2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/145/4d5d0fb...9801ee2.html" title="Last updated on Jan 23, 2020, 5:49 PM UTC (9801ee2)">Diff</a>
> Add Vi Nguyen to Editors

- index.bs
See #155
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/156.html" title="Last updated on Jun 29, 2020, 3:30 PM UTC (3183cd9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/156/a9bdf79...3183cd9.html" title="Last updated on Jun 29, 2020, 3:30 PM UTC (3183cd9)">Diff</a>
> Clarify smooth=true criteria

- security-privacy-questionnaire.md
Pulling in new/revised questions from the editors draft of the
questionnaire.
> Update security-privacy-questionnaire.md w/ latest questions.

- .github/workflows/pr-push.yml
- explainer.md
- index.bs
Also drop the "previous version" link to avoid the duplicated link bug when the spec gets published to /TR.
Default branch name needs to be updated before that PR gets merged. Happy to take care of that.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/178.html" title="Last updated on May 4, 2021, 3:31 PM UTC (0a26293)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/178/361fce5...0a26293.html" title="Last updated on May 4, 2021, 3:31 PM UTC (0a26293)">Diff</a>
> Rename default branch name to "main"

- explainer.md
- index.bs
Fixes #190
***
<a href="https://pr-preview.s3.amazonaws.com/drkron/media-capabilities/pull/191.html" title="Last updated on Apr 7, 2022, 1:23 PM UTC (98692c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/191/7cfc693...drkron:98692c6.html" title="Last updated on Apr 7, 2022, 1:23 PM UTC (98692c6)">Diff</a>
> Add webrtc examples

- index.bs
Fixes #181.
***
<a href="https://pr-preview.s3.amazonaws.com/drkron/media-capabilities/pull/195.html" title="Last updated on Apr 20, 2022, 10:18 AM UTC (b3f50e6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/195/55cf43a...drkron:b3f50e6.html" title="Last updated on Apr 20, 2022, 10:18 AM UTC (b3f50e6)">Diff</a>
> Fix broken RFC links

- index.bs
This PR fixes another minor typo I found.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 12, 2024, 4:20 PM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [HTML Diff Service](http://services.w3.org/htmldiff) - The HTML Diff Service is used to create HTML diffs of the spec changes suggested in a pull request.
:link: [Related URL]([object Object])
```
<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
```
_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an …
> Fix typo in Security and Privacy Considerations section

- index.bs
Add myself as a co-editor to the spec :)
***
<a href="https://pr-preview.s3.amazonaws.com/mfoltzgoogle/media-capabilities/pull/228.html" title="Last updated on Aug 30, 2024, 11:11 AM UTC (757e986)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/228/1d52c00...mfoltzgoogle:757e986.html" title="Last updated on Aug 30, 2024, 11:11 AM UTC (757e986)">Diff</a>
> Add myself as co-editor.

- index.bs
This closes #184 using the solution proposed in that issue.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/230.html" title="Last updated on Sep 17, 2024, 8:28 PM UTC (e68a9e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/230/ee7f0b6...e68a9e7.html" title="Last updated on Sep 17, 2024, 8:28 PM UTC (e68a9e7)">Diff</a>
> Clarify the meaning of  the "file" MediaDecodingType
